[gpu] check cuda and gpus without installing anything

diff --git a/.github/workflows/run-tests-gpu.yaml b/.github/workflows/run-tests-gpu.yaml
--- a/.github/workflows/run-tests-gpu.yaml
+++ b/.github/workflows/run-tests-gpu.yaml
@@ -27,14 +27,21 @@ jobs:
               enable-cache: false
               python-version: '3.10'
 
+          # - name: Debug | Verify CUDA installation
+          #   run: |
+          #     nvcc --version && \
+          #     echo "Installed CUDA version is: ${{ steps.cuda-toolkit.outputs.cuda }}" && \
+          #     echo "CUDA installation path is: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}" || \
+          #     echo "CUDA not found"
+
           - name: Setup | Dependencies
             run: uv sync --frozen --extra gpu --no-group docs
 
-          - name: Setup | Install CUDA
-            id: cuda-toolkit
-            uses: Jimver/cuda-toolkit@v0.2.21
-            with:
-              cuda: '12.4.0'
+          # - name: Setup | Install CUDA
+          #   id: cuda-toolkit
+          #   uses: Jimver/cuda-toolkit@v0.2.21
+          #   with:
+          #     cuda: '12.4.0'
 
           - name: Setup | Verify CUDA installation
             run: |
@@ -43,18 +50,18 @@ jobs:
               echo "CUDA installation path is: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}" || \
               echo "CUDA not found"
 
-          - name: Check PyTorch and CUDA version
+          - name: Debug | Check PyTorch and CUDA version
             run: |
               python -c "import torch; print('Torch:', torch.__version__); print('CUDA available:', torch.cuda.is_available()); print('CUDA version:', torch.version.cuda)"
+
+          - name: Debug | Check available GPU-s
+            run: nvidia-smi || echo "No GPU available"
 
           - name: Run tests -> end_to_end -> sequential
             run: CUDA_VISIBLE_DEVICES=0 uv run pytest --log-cli-level=INFO tests/end_to_end/test_tabular_sequential.py
 
           - name: Run tests -> end_to_end -> sequential context
-            run: |
-              export NVIDIA_VISIBLE_DEVICES=all
-              nvidia-smi
-              uv run pytest --log-cli-level=INFO tests/end_to_end/test_tabular_sequential_context.py
+            run: uv run pytest --log-cli-level=INFO tests/end_to_end/test_tabular_sequential_context.py
 
           - name: Run tests -> end_to_end all except sequential
             run: uv run pytest --log-cli-level=INFO --ignore=tests/end_to_end/test_tabular_sequential.py --ignore=tests/end_to_end/test_tabular_sequential_context.py tests/end_to_end/
